### PR TITLE
Projectile goes down

### PR DESCRIPTION
**Pull request by NinoDavids**
- now the projectile goes down when its getting shot

### CODE REVIEW

**Comment by RoyDuijndam1** [comment]
Dont forget to delete the print statement

**Comment by NinoDavids** [comment]
fair point

**Comment by Studeeric** [comment]
It doesn't go up again when the projectile distance is increased (see an example with a canon and a spring)

**Comment by Studeeric** [comment]
Making an arch can actualluy prevent objects from interacting with the projectile.. Coming up with a better solution

**Pull request merged**
